### ISSUE TITLE
Fields: if a field was inside more than one category.

### ISSUE THREAD

**Issue by TheNextStage** [cprojectsorg/Qatdatabase#36]
### - Steps to reproduce the issue
- Add new field and choose at least two categories (but not one), Then go to item posting form and choose any of categories which is chosen in the new field, then the field won't appear.

**Comment by CprojectsDev** [comment]
This is happening because my script doesn't split the field's categories (if it was in multiple/various categories), so it takes the whole categories as one category (like: 1,2,3,4) instead of making it separated string, i am working on this issue in fact, See: https://github.com/cprojectsorg/Qatdatabase/commit/97b2bf5fc53c3b63667c68b15405f497fc3391b1#diff-c1011807acbf80fdacb4390815315619R32

**Comment by CprojectsDev** [comment]
https://github.com/cprojectsorg/Qatdatabase/commit/c9870cceac12559373de57c64aa4af453d71c410
